"""create freight rates table

Revision ID: 557add53a25f
Revises: 85894d7040cb
Create Date: 2026-09-06 17:17:29.462735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '557add53a25f'
down_revision: Union[str, Sequence[str], None] = '85894d7040cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'freight_rates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('origin_country', sa.String(length=100), nullable=False),
        sa.Column('destination_region', sa.String(length=100), nullable=False),
        sa.Column('cargo_type', sa.String(length=100), nullable=False),
        sa.Column('vessel_class', sa.String(length=50), nullable=False),
        sa.Column('forecast_date', sa.Date(), nullable=False),
        sa.Column('freight_rate', sa.Float(), nullable=True),
        sa.Column('currency', sa.String(length=10), nullable=False),
        sa.Column('unit', sa.String(length=50), nullable=False),
        sa.Column('model_version', sa.String(length=100), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('data_status', sa.String(length=20), nullable=False),
        sa.Column('source', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_freight_rates_id'),
        'freight_rates',
        ['id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_freight_rates_id'),
        table_name='freight_rates'
    )
    op.drop_table('freight_rates')
    # ### end Alembic commands ###