"""create vessels table

Revision ID: 5c44cf96eb48
Revises: 04026bcac3cb
Create Date: 2026-09-06 16:16:33.617233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c44cf96eb48'
down_revision: Union[str, Sequence[str], None] = '04026bcac3cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vessels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('vessel_class', sa.String(length=50), nullable=False),
    sa.Column('dwt', sa.Float(), nullable=True),
    sa.Column('loa_m', sa.Float(), nullable=True),
    sa.Column('beam_m', sa.Float(), nullable=True),
    sa.Column('draft_m', sa.Float(), nullable=True),
    sa.Column('cargo_types', sa.String(length=500), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('data_status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vessels_id'), 'vessels', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vessels_id'), table_name='vessels')
    op.drop_table('vessels')
    # ### end Alembic commands ###
