"""create voyages table

Revision ID: 623e7038ce9b
Revises: 557add53a25f
Create Date: 2026-09-06 17:39:11.512681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623e7038ce9b'
down_revision: Union[str, Sequence[str], None] = '557add53a25f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('max_draft_m', sa.Float(), nullable=True),
    sa.Column('max_loa_m', sa.Float(), nullable=True),
    sa.Column('max_beam_m', sa.Float(), nullable=True),
    sa.Column('annual_capacity_tonnes', sa.Float(), nullable=True),
    sa.Column('utilization_percent', sa.Float(), nullable=True),
    sa.Column('average_waiting_hours', sa.Float(), nullable=True),
    sa.Column('cargo_types', sa.String(length=500), nullable=True),
    sa.Column('data_status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ports_id'), 'ports', ['id'], unique=False)
    op.create_table('voyages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_type', sa.String(length=100), nullable=False),
    sa.Column('quantity_tonnes', sa.Float(), nullable=False),
    sa.Column('origin_country', sa.String(length=100), nullable=False),
    sa.Column('destination_region', sa.String(length=100), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('charter_start_date', sa.Date(), nullable=True),
    sa.Column('charter_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voyages_id'), 'voyages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voyages_id'), table_name='voyages')
    op.drop_table('voyages')
    op.drop_index(op.f('ix_ports_id'), table_name='ports')
    op.drop_table('ports')
    # ### end Alembic commands ###
