from datetime import date
from pathlib import Path
from typing import Any, Dict

import pandas as pd

from app.ml.forecasting.future_inference import forecast_future
from app.ml.forecasting.model_loader import load_xgboost_model


FEATURE_DATA_PATH = (
    Path(__file__).resolve().parents[3]
    / "data"
    / "processed"
    / "freight_model_features.csv"
)


FEATURES = [
    "freight_lag_1",
    "freight_lag_3",
    "freight_lag_6",
    "freight_lag_12",
    "freight_rolling_mean_3",
    "freight_rolling_mean_6",
    "freight_rolling_mean_12",
    "freight_rolling_std_3",
    "baltic_dry_index_lag_1",
    "baltic_dry_index_lag_3",
    "brent_price_lag_1",
    "brent_price_lag_3",
    "wti_price_lag_1",
    "wti_price_lag_3",
    "dxy_index_lag_1",
    "dxy_index_lag_3",
    "vix_lag_1",
    "vix_lag_3",
    "gpr_index_lag_1",
    "gpr_index_lag_3",
    "thermal_coal_price_lag_1",
    "thermal_coal_price_lag_3",
    "month_num",
    "quarter",
    "month_sin",
    "month_cos",
]


_cached_features: pd.DataFrame | None = None


def load_feature_data() -> pd.DataFrame:
    global _cached_features

    if _cached_features is not None:
        return _cached_features

    if not FEATURE_DATA_PATH.exists():
        raise FileNotFoundError(
            f"Forecast feature dataset not found: {FEATURE_DATA_PATH}"
        )

    df = pd.read_csv(FEATURE_DATA_PATH)

    if "date" not in df.columns:
        raise ValueError(
            "Forecast feature dataset must contain a date column."
        )

    missing_features = [
        feature
        for feature in FEATURES
        if feature not in df.columns
    ]

    if missing_features:
        raise ValueError(
            "Forecast feature dataset is missing required features: "
            + ", ".join(missing_features)
        )

    df["date"] = pd.to_datetime(df["date"]).dt.date

    _cached_features = df

    return df


def _future_forecast(forecast_date: date) -> Dict[str, Any]:
    """Run the future ML pipeline through its public forecasting boundary."""

    result = forecast_future(forecast_date)

    return {
        "forecast_rate": result["predicted_rate"],
        "currency": result["currency"],
        "unit": result["unit"],
        "forecast_date": forecast_date,
        "model_name": result["model_name"],
        "model_version": result.get("model_version"),
        "confidence": None,
        "data_status": result["data_status"],
        "message": (
            "Future market freight benchmark generated by the "
            "production XGBoost model using forecast exogenous inputs."
        ),
    }


def predict_freight(
    forecast_date: date,
) -> Dict[str, Any]:
    df = load_feature_data()

    # The training dataset is monthly.
    # Convert any requested date to the first day of its month
    # for feature-row lookup.
    feature_date = (
        pd.Timestamp(forecast_date)
        .to_period("M")
        .to_timestamp()
        .date()
    )

    matching_rows = df[df["date"] == feature_date]

    # -------------------------------------------------------------
    # Future forecast path
    #
    # The historical feature dataset ends before future dates.
    # Delegate all future feature generation and recursive forecasting
    # to the ML package's public forecast_future() boundary.
    # -------------------------------------------------------------
    if matching_rows.empty:
        latest_feature_date = df["date"].max()

        if forecast_date > latest_feature_date:
            return _future_forecast(forecast_date)

        return {
            "forecast_rate": None,
            "currency": "USD",
            "unit": "USD/day",
            "forecast_date": forecast_date,
            "model_name": "Round 1 XGBoost",
            "model_version": None,
            "confidence": None,
            "data_status": "UNAVAILABLE",
            "message": (
                "Required forecast feature row is unavailable for "
                f"the month containing {forecast_date}."
            ),
        }

    row = matching_rows.iloc[0]

    feature_frame = pd.DataFrame(
        [[row[feature] for feature in FEATURES]],
        columns=FEATURES,
    )

    if feature_frame.isnull().any().any():
        return {
            "forecast_rate": None,
            "currency": "USD",
            "unit": "USD/day",
            "forecast_date": forecast_date,
            "model_name": "Round 1 XGBoost",
            "model_version": None,
            "confidence": None,
            "data_status": "UNAVAILABLE",
            "message": (
                "Required forecast features contain missing values."
            ),
        }

    model, model_version = load_xgboost_model()

    prediction = float(
        model.predict(feature_frame)[0]
    )

    return {
        "forecast_rate": prediction,
        "currency": "USD",
        "unit": "USD/day",
        "forecast_date": forecast_date,
        "model_name": "Round 1 XGBoost",
        "model_version": model_version,
        "confidence": None,
        "data_status": "KNOWN",
        "message": (
            "Market freight benchmark generated by the production "
            "Round 1 XGBoost model."
        ),
    }
